### ISSUE TITLE
Cannot find module 'lru-cache' with version 0.8.0

### ISSUE THREAD

**Issue by arey** [gruntjs/grunt-contrib-jshint#137]
I've tried to udpate grunt-contrib-jshint version from 0.7.2 to 0.8.0 on my https://github.com/arey/angular-musicbrainz project. But I've got the following error message :

```
D:\dev\angular-musicbrainz>grunt jshint
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'lru-cache'
Warning: Task "jshint" not found. Use --force to continue.
Aborted due to warnings.
```

For your information, I'm on Windows 7 64 bits.

**Comment by saraivajunior** [comment]
nao funcionou
