### ISSUE TITLE
Allow multiple reporters for a single run

### ISSUE THREAD

**Issue by dharkness** [gruntjs/grunt-contrib-jshint#169]
When running JSHint in Jenkins, we want the regular output for the build log (emailed to developer for quick fixes) and the checkstyle reporter for the Jenkins plugin.

Is this possible? If not, it would be very handy so we don't have to run JSHint twice.

**Comment by betterphp** [comment]
Just for anyone else finding this - we had the same problem and solved it by create a custom reporter that called the other two we wanted.

~~~js
var stylish = require("jshint-stylish");
// Weird double require() as the module exports the path to its reporter
var junit = require(require("jshint-junit-reporter"));

exports.reporter = function(results, data, opts) {
	stylish.reporter(results, data, opts);
	opts.outputFile = './test-results/jshint.xml';
	junit.reporter(results, data, opts);
};
~~~
then in the gruntfile set the path to this file
~~~
jshint: {
			options: {
				reporter: './jshint-reporter.js',
				...
~~~
