### ISSUE TITLE
`options` is broken

### ISSUE THREAD

**Issue by UltCombo** [gruntjs/grunt-contrib-jshint#180]
Considering these options (passed either in the task's `options` or `jshintrc`):

``` json
{
    "node": true,
    "esnext": true
}
```

It seems like the `esnext` option is not recognized when passing `"node": true` together with it. This issue **does not happen** when running `jshint` directly from the CLI, so I believe it is an issue in this Grunt plugin.

**Comment by nobleach** [comment]
I'm experiencing this same exact thing. `import` and `class` are not recognized even though I have `'esnext': true` in my options.

**Comment by UltCombo** [comment]
I can reopen this issue if you'd like @nobleach, but seeing as I no longer use JSHint nor Grunt I'll not have much interest in this issue.

**Comment by nobleach** [comment]
I want to be extremely sure I'm not doing something wrong. So I suppose let's just ignore it for now. Thanks!
