### ISSUE TITLE
README.md section ignoring-specific-warnings example is wrong for "version": "0.10.0",

### ISSUE THREAD

**Issue by bhonnegowda** [gruntjs/grunt-contrib-jshint#186]
grunt.initConfig({
  jshint: {
    ignore_warning: {
      options: {
        '-W015': true,
      },
      src: ['**/*.js'],
    },
  },
});

does not work. please correct it.

**Comment by arthurvr** [comment]
This line is incorrect:

```
src: ['*/.js'],
```

That should be

```
src: ['**/*.js'],
```

or something similar. This is actually correct in the readme so I think this issue can be closed.

**Comment by arthurvr** [comment]
Ping? This issue can be closed. See the comment above.
