### ISSUE TITLE
.jshintignore support not working

### ISSUE THREAD

**Issue by jawshooah** [gruntjs/grunt-contrib-jshint#188]
I have the following configuration:
```js
{
    options: {
        jshintrc: '.jshintrc'
    },
    all: ['**/*.js']
}
```
And the following `.jshintignore`:
```
node_modules
bower_components
lib/external
vendor
help
steal
funcunit
**/*.min.js
**/production.js
```
Running `jshint . --exclude-path=.jshintignore` from the command line takes very little time, and behaves as expected.

However, running `grunt jshint:all` takes *forever*, and dumps linter output for files in literally every directory specified in my `.jshintignore`. What's going on here?

**Comment by jawshooah** [comment]
Alright, I've created a minimal example. My file hierarchy is thus:
```
.
├── .jshintignore
├── .jshintrc
├── Gruntfile.js
├── foo.js
└── node_modules
    ├── grunt
    └── grunt-contrib-jshint
```
`.jshintignore`:
```
node_modules
```
`.jshintrc`:
```json
{
    "strict": false,
    "globals": {
        "module": true
    }
}
```
`Gruntfile.js`:
```js
module.exports = function(grunt) {
    grunt.initConfig({
        jshint: {
            all: ['**/*.js']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-jshint');
};
```
`foo.js`:
```js
var foo = 'foo'
```
Output of `jshint .`:
```bash
foo.js: line 1, col 16, Missing semicolon.

1 error
```
Output of `grunt jshint:all`:
```js
Running "jshint:all" (jshint) task

   foo.js
      1 |var foo = 'foo'
                        ^ Missing semicolon.
   node_modules/grunt-contrib-jshint/node_modules/hooker/child.js
     24 |  var len = Object.keys(unfinished).length
                                                   ^ Missing semicolon.
     99 |}
          ^ Missing semicolon.
   node_modules/grunt-contrib-jshint/node_modules/hooker/dist/ba-hooker.js
     44 |    } else if (props == null) {
                              ^ Use '===' to compare with 'null'.
     73 |    if (options == null) {
                         ^ Use '===' to compare with 'null'.
   node_modules/grunt-contrib-jshint/node_modules/hooker/dist/ba-hooker.min.js
   ...
```

**Comment by BigstickCarpet** [comment]
+1

**Comment by yeahoffline** [comment]
same here, my .jshintignore looks like

```javascript
node_modules/*
*/node_modules/*
!*/node_modules/internal-*
```

It works fine using jshint cli

**Comment by mgimenez** [comment]
I have the same problem, any solution?

**Comment by vladikoff** [comment]
I added extra tests for both cases - ignores option and the included test file, see https://github.com/gruntjs/grunt-contrib-jshint/blob/master/Gruntfile.js#L45

Please check the formatting of your ignore file. If you still have issues please either fork the repo and make tests fail or provide a failing test case.

**Comment by vladikoff** [comment]
![](http://v14d.com/i/55087e7f48b65.jpg)

**Comment by mgimenez** [comment]
Excellent, had misunderstood the doc! : / 
Thanks for support!

**Comment by yeahoffline** [comment]
just add a negate line to .jshintignore and tests will fail like:

.jshintignore
```javascript
test/fixtures/dontlint.txt
node_modules/**
!nodemodule.js
```

**Comment by vladikoff** [comment]
@yeahoffline probably related to https://github.com/jshint/jshint/issues/1917 ?

**Comment by yeahoffline** [comment]
Yes! Thank you!
