### ISSUE TITLE
0.11.x version of jshint runs much slower than previous version

### ISSUE THREAD

**Issue by carrierdown** [gruntjs/grunt-contrib-jshint#201]
Any idea what may be causing this? With version 0.10.x jshinting my project takes around 4 seconds. After updating to version 0.11.x the same process takes over a minute. I have reverted back to the previous version for now, but would like to inform you about this problem.

**Comment by trobertsonsf** [comment]
bump.   Our linting with 0.10.x took about 20 seconds, with 0.11.2 it takes over 2 minutes! Reverted to 0.10 and it's back down to 15 seconds.

**Comment by gruber76** [comment]
What platform (OS and terminal) are you using, how long is a successful output, and what does it look like in debug mode?

**Comment by trobertsonsf** [comment]
Macbook Pro OS X Yosimite 
Default Mac Terminal
Not sure what you mean by how long is a successful output? Are you talking about time it took to run or the amount (lines) written to the console?

**Comment by JohnONolan** [comment]
I'm seeing the same thing (5+ minutes to run) on one machine, and a few seconds on another. Only difference is that the fast one is on Node 0.12.x and the slow one on Node 0.10.x

**Comment by trobertsonsf** [comment]
I'm on Node 0.12.x and it's still sloooooowwww. Any update?

**Comment by trobertsonsf** [comment]
Any update here? This is really killing my project.

**Comment by Skinner927** [comment]
+1 same for us here.

**Comment by Urik** [comment]
+1
Windows 10 on an i7 with 8gb of ram, takes 5 minutes for me on a project of my work. Used to take the same on an i5 with windows 7. Node 4.2.0. A coworker that uses windows has the same issue. The mac guys don't suffer from it though.

**Comment by RichardSimko** [comment]
I'm having similar issues. Running `grunt jshint` takes around 6 seconds for my project, whereas running `jshint` with the same parameters takes about 0.6 seconds. Of course it's not much in terms of time but it's an order of magnitude slower which doesn't makes sense.

As a comparison JSCS takes around 1.3 seconds when running though grunt and 0.6 when running standalone.

**Comment by segg3r** [comment]
+1

**Comment by ryadiv** [comment]
2 years later, same here.
