### ISSUE TITLE
Syntax error on classes, using esnext, runs forever

### ISSUE THREAD

**Issue by felipenmoura** [gruntjs/grunt-contrib-jshint#206]
When there is an error on a class, in ES2015 as

```js
class Foo {
    someProperty : "bar", // invalid
    someMethod () {}
}
```

By running the task, it hangs forever on `Running "jshint:all" (jshint) task`. If we simply comment the "someProperty" line, it works just fine.

**Comment by sindresorhus** [comment]
That's not valid ES6 syntax.

**Comment by felipenmoura** [comment]
I think I didn't make it clear! :p 
Yes...that is not valid ES6 syntax...so, that is the message I expected to get, instead of an infinity loop(or whatever it does internally).
I don't think that holding some task forever is the ideal feedback about such a syntax error!
