### ISSUE TITLE
JSHint updated

### ISSUE THREAD

**Issue by renie** [gruntjs/grunt-contrib-jshint#209]
When JSHint releases a new version, this grunt lib do not increase a number version. So for using a new version of JSHint we need to remove and re-install this lib.

An issue I had, just to exemplify: 

In my local environment grunt-contrib-jshint works perfectly, but crashes when I applied last changes to my server. After a little investigation I discovered that grunt jshint lib was in same version on both environments, but the dependency 'jshint' of grunt-contrib-jshint was on 2.8.0 on my local and 2.7.0 on my server.

**Comment by sindresorhus** [comment]
That's how npm and semver works.

**Comment by renie** [comment]
SEMVER says:

"What should I do if I update my own dependencies without changing the public API?(...) Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment."

As I understand, if this lib depends on another and this dependency introduce a new feature, I should increment a minor level.

Am I wrong?
