### ISSUE TITLE
Include jshint error/warning code in message

### ISSUE THREAD

**Issue by billwolckenlmco** [gruntjs/grunt-contrib-jshint#21]
One feature I have found useful in the jshint command-line interface is the ability to include the error/warning code in each message.  For example, the code for "Line is too long" is "W101".  Since jshint allows messages to be suppressed at the individual message code level (via comments in the file) and thus be more granular than the named options allow, having the code in the output message is useful for knowing what code to use.

Currently, grunt-contrib-jshint doesn't display the code anywhere in the output text.

**Comment by zebulonj** [comment]
Not seeing the error code in messages anymore. Am I missing something?
