### ISSUE TITLE
JSHint aborted due to warnings. Why?

### ISSUE THREAD

**Issue by rclaes1995** [gruntjs/grunt-contrib-jshint#213]
![image](https://cloud.githubusercontent.com/assets/11699918/8872479/a8ef7342-31fd-11e5-9af6-190a38cdea0a.png)

Hi! I'm trying Grunt for the first time. Installed JSHINT and running it but it keeps aborting no matter what. I've tried several files; not limiting to Gruntfile.js, but still the same issue.

This is my config:

    jshint: {
        options: {
            curly: true,
            immed: true,
            latedef: true,
            newcap: true,
            noarg: true,
            sub: true,
            undef: true,
            boss: true,
            eqnull: true,
            browser: true
        },
        all: ['Gruntfile.js']
    }

**Comment by sindresorhus** [comment]
It aborts because you have a JSHint warning. It's right there in your screenshot.
