### ISSUE TITLE
eval is evil thrown in wrong occasions

### ISSUE THREAD

**Issue by GuyMograbi** [gruntjs/grunt-contrib-jshint#225]
I wrote the following code

```
var foo = {
    eval:function(){

    }
};

foo.eval();
```

and got `eval is evil` warning. however this is clearly not the scenario in which it should be thrown.. 
using /*jshint -W061 */ for now, but should not write warning on this.

**Comment by sindresorhus** [comment]
Should be opened on the JSHint issue tracker.
