### ISSUE TITLE
jshint wont ignore certain folders or files

### ISSUE THREAD

**Issue by paladox** [gruntjs/grunt-contrib-jshint#228]
Hi when running jscs with jshint it wont ignore certain files or folders if you added it to the .jshintignore file.

Workaround is to add it like for example

'!node_modules/**',

to the jshint part so like

		jshint: {
			options: {
				jshintrc: true
			},
			all: [
				'*.js',
				'**/*.js',
				'!node_modules/**',
				'!js/overthrow.js'
			]
		},

But with jscs I have it like

		jscs: {
			src: '<%= jshint.all %>'
		},

But wont ignore the files. Please help. This may be a bug.

**Comment by jrcryer** [comment]
Hi @paladox, were you expecting the ignore list from your jshintrc file to be passed to the `jscs` task? The jshintrc file is passed to `jshint` module and isn't read so it will not be passed onto the `jscs` task.  I'd suggest you look at having a `.jscs` file (see example: [.jscs config](https://github.com/jscs-dev/node-jscs/blob/master/.jscsrc)).

**Comment by paladox** [comment]
Hi I have a .jscs file but in jshint the proboes happends too. The workaround is to do '!example/**' that's an example. You have to copy wants in the jshintignore file into the grunt file.

**Comment by jrcryer** [comment]
Sorry - misunderstood what you were trying to do but I think I've got a working example [gist](https://gist.github.com/jrcryer/5374ea9422ee904cee9a)

**Comment by paladox** [comment]
Oh.

Well the problem is jshint is ignoring the jshintignore file. So you have to also add the ignored jshint to grunt jshint.

**Comment by jrcryer** [comment]
@paladox - did you see the gist? I think it does what you want to do.  I've ignored the `bad.js` using `.jshintignore` file. Ta
