### ISSUE TITLE
Update to JSHint 2.9.0+

### ISSUE THREAD

**Issue by godban** [gruntjs/grunt-contrib-jshint#230]
We have an issue with https://github.com/jshint/jshint/issues/2771, please update

**Comment by furyscript** [comment]
+1

**Comment by ddcovery** [comment]
+1

**Comment by godban** [comment]
Oh, no worries. Switched to ESLint.

**Comment by vladikoff** [comment]
There is no 2.9.0 on npm, see https://github.com/jshint/jshint/releases

**Comment by godban** [comment]
@vladikoff https://github.com/jshint/jshint/commit/925a706af6dd1db31d1a70cd6a00f3961d72b083

**Comment by vladikoff** [comment]
> @vladikoff jshint/jshint@925a706

Again 2.9.0 was pulled from npm. Read the releases page: 
```
Version 2.9.0 was revoked shortly after its release due to a number of
regressions.
```
rc.1 is not available on npm either

**Comment by jkiimm** [comment]
@vladikoff I can see now `2.9.1-rc1` version via `npm view jshint versions`. but, are you waiting for not rc version?

**Comment by vladikoff** [comment]
> but, are you waiting for not rc version?

pretty much, if you want support for 2.9.1-rc1 just fork this and adjust the version
