### ISSUE TITLE
ECMA6 script

### ISSUE THREAD

**Issue by furyscript** [gruntjs/grunt-contrib-jshint#231]
How can I validate ecma6 script like this

```javascript
var string = `
    Hello
`;
```
Thanks,

**Comment by vladikoff** [comment]
wrong place to ask questions, try stackoverflow or the jshint repo

**Comment by furyscript** [comment]
But this plugin for grunt support es6 validation?

**Comment by furyscript** [comment]
I think do not support
`esversion	
This option is used to specify the ECMAScript version to which the code must adhere. It can assume one of the following values:

3 - If you need your program to be executable in older browsers—such as Internet Explorer 6/7/8/9—and other legacy JavaScript environments
5 - To enable syntax first defined in the ECMAScript 5.1 specification. This includes allowing reserved keywords as object properties.
6 - To tell JSHint that your code uses ECMAScript 6 specific syntax. Note that not all browsers implement them.
`
If I try it the options esversion not work!

**Comment by sidshetye** [comment]
@vladikoff , I think the OP was asking if you support ES6 ... for example, with this gruntfile ...
```
 jshint: {
      src: [ 
        '<%= app_files.js %>'
      ],
      test: [
        '<%= app_files.jsunit %>'
      ],
      gruntfile: [
        'Gruntfile.js'
      ],
      options: {
        curly: true,
        immed: true,
        newcap: false,
        noarg: true,
        sub: true,
        boss: true,
        eqnull: true,
        esversion: 6
      },
      globals: {}
    },

```
and `    "grunt-contrib-jshint": "^0.11.0"` still gives

```
Bad option: 'esversion'.
```

**Comment by AChaoZJU** [comment]
@sidshetye 
Thanks, it works.

**Comment by jlnmay** [comment]
Hi, I have a similar error. 
I can't execute grunt jshint because it throws errors. 
For example this 
1 |"use strict";
         ^ Use the function form of "use strict".

I am trying to use in a built project ES6 features.
I tried to add 'esversion': 6 attribute to the jshint's options but it still is not working, also tried to add in the root project directory a .jshintrc file with the same attribute but with no success.

this is my configuration 

    babel: {
            options: {
                presets: ['babel-preset-es2015']
            },
            dist: {
                files: {
                    "app/src/portal.js": "app/src/portalES6.js"
                }
            }
        },
        jshint: {
            files: ['Gruntfile.js', 'app/src/settings.js', 'app/src/portal.js'],
            options: {
                // options here to override JSHint defaults
                globals: {
                    jQuery: true,
                    console: true,
                    module: true,
                    document: true
                },
                laxcomma: true,
                esversion: 6
            }
        }

Kind regards.

Julián May

**Comment by helgatheviking** [comment]
Still experiencing a problem with this. Adding `esversion: 6` to the gruntfile options OR adding "esversion":6` in the `.jshintrc` file. Either way still results in es6-related notices when running jshint via grunt.
