### ISSUE TITLE
jshint eqeqeq: false

### ISSUE THREAD

**Issue by kuangcaibao** [gruntjs/grunt-contrib-jshint#236]
```
// Gruntfile.js
...
jshint: {
  options: {
    eqeqeq: false,
    eqnull: true
  },
  all: [ 'test/*.js' ]
}
...
```

```
// test/test.js
var foo = function(v) {
    if (v == "1") {
        console.log("v equals 1");
    } else {
        console.log("v not equals 1");
    }
};
```

We run the command grunt jshint:all in command line, it went well. When i change the number 1 in test.js file to 0, like

```
if(v == "0")
```

it comes an error, likes the eqeqeq does not work. Hope your answers, thanks

**Comment by XhmikosR** [comment]
This kind of issues should be reported upstream.
