### ISSUE TITLE
Default grunt reporter depends implicitly on the `colors` package

### ISSUE THREAD

**Issue by jurko-gospodnetic** [gruntjs/grunt-contrib-jshint#237]
Default grunt reporter depends implicitly on the `colors` package because it expects to be able to construct **bold** output by simply reading the `String.prototype.bold` property set up by the `colors` package.

If the `colors` package `String.prototype` modifications are not available for some reason, reporting an error such as an unused variable will fail and report only:
```
Warning: undefined is not a function Use --force to continue.
```
which is not really helpful as it does not tell you neither what the problem is or which file it originated from.

Reasons why the current implementation is problematic:
- `colors` package is not listed as a dependency in this project's `packages.json`
- `colors` package needs to be loaded in such a way that it updates the `String.prototype` which may cause problems by itself since other packages (e.g. `core-js`, as used by karma) may reset that `String.prototype`

This should be corrected by doing the following:

1. declare the `colors` dependency in the project's `packages.json`
2. import `colors/safe` to not modify the global `String.prototype`
3. replace `grunt.log.writeln((result.file ? '   ' + result.file : '').bold);` with `grunt.log.writeln(colors.bold(result.file ? '   ' + result.file : '');` to apply the **bold** formatting without depending on `String.prototype` modifications

**Comment by shama** [comment]
Fixed with https://github.com/gruntjs/grunt-contrib-jshint/commit/9527f8f8f75e0386a67003fdfd122dc7cf698e68
