### ISSUE TITLE
Provide Linux Installation Command

### ISSUE THREAD

**Issue by EmpireWorld** [gruntjs/grunt-contrib-jshint#270]
Please provide linux installation command:
```
sudo npm install grunt-contrib-jshint --save-dev
```
for fast developers. :+1: 
fun.

**Comment by vladikoff** [comment]
do not use `sudo` with npm install. if you have to use `sudo` with npm then your system is probably misconfigured.

**Comment by EmpireWorld** [comment]
@vladikoff What do you mean misconfigured?
