### ISSUE TITLE
Updated Release Coming?

### ISSUE THREAD

**Issue by andrew-st-angelo-77media** [gruntjs/grunt-contrib-jshint#284]
First off, thank you for all the work you're doing.  I don't want to look a gift horse in the mouth.

Your most recent release works off of JShint 2.9.0.  That package is now up to [v2.9.6](https://github.com/jshint/jshint/releases), which, in the two years since v2.9.0, has included a great deal of support for ES6+ features/syntax.  I noticed that your recent commits have continued to increase the version of JShint this package relies on, but no formal release has been issued.

So, my question is, is one coming and is there a target date?

**Comment by XhmikosR** [comment]
See #285

**Comment by vladikoff** [comment]
It's live!

**Comment by andrew-st-angelo-77media** [comment]
You guys rock! 🤘 
Thank you!
