### ISSUE TITLE
Update Jshint dependency

### ISSUE THREAD

**Issue by cpmachado** [gruntjs/grunt-contrib-jshint#286]
As of recently, I've seen need to use ecmascript 8's async await. This available only from jshint ^2.10.0.
When are you expecting to update Jshint dependency?

Currently we are 2.9.6

Thanks in advance

**Comment by 1ftskank** [comment]
Yes, we'd love this too! Thanks!

**Comment by rarajks** [comment]
Please update the Jshint dependency

**Comment by cpmachado** [comment]
All solved
