### ISSUE TITLE
Errors when running against targets

### ISSUE THREAD

**Issue by bclinkinbeard** [gruntjs/grunt-contrib-jshint#37]
I am attempting to use the syntax shown in the README to make violations halt release builds only, but getting a weird error when using the targets. My syntax is as follows:

```
jshint: {
    options: {
        jshintrc: '.jshintrc'
    },
    dev: {
        options: {
            force: true
        },
        files: ['./Gruntfile.js', '<%= cfg.js_src %>', '!<%= cfg.libs_dir %>/**']
    },
    release: {
        files: ['./Gruntfile.js', '<%= cfg.js_src %>', '!<%= cfg.libs_dir %>/**']
    }
}
```

and the error I get is `Warning: Cannot use 'in' operator to search for 'src' in ./Gruntfile.js Use --force to continue.` with an exit code of 3.

**Comment by ccorcos** [comment]
Im confused -- what about the files array format? http://gruntjs.com/configuring-tasks#files-array-format
