### ISSUE TITLE
Reporter option

### ISSUE THREAD

**Issue by ffesseler** [gruntjs/grunt-contrib-jshint#46]
When using the new reporter option, a lot of errors are output with the message : Bad option: 'reporter'. 

here is my grunt config :

```
jshint: {
      options: {
        "reporter" : "checkstyle",
        "force" : true,
        "browser": true,
        "node": false,
        "globalstrict" : true,
        globals: {
          angular : true,
          console : true,
          i18n : true,
          $ : true
        }
    },
    src: [
      '<%= dirs.js %>/**/*.js'
    ]
```

By the way, is it possible to specify a xml file output for the checkstyle reporter?

**Comment by atdiff** [comment]
@ffesseler did you ever figure out a way to accomplish multiple reporterOutputs?  I have a need to do one to the console and one to a file but using the same data.  I can do multiple targets but that seems like a waste of processing time.  And if one target fails, it won't continue unless I use force - which I'd rather not.

**Comment by ffesseler** [comment]
@atdiff We've switched to eslint long time ago and I don't really remember, sorry
