### ISSUE TITLE
fail noise/alert with force

### ISSUE THREAD

**Issue by forresto** [gruntjs/grunt-contrib-jshint#48]
I have a custom task which runs `['connect', 'watch']` to run a server and run jshint when files are changed. I set watch to use force, so a failed lint wouldn't stop the server:

```
  watch: {
    scripts: {
      files: ['Gruntfile.js', 'src/*.js', 'src/**/*.js'],
      tasks: ['jshint:force'],
      options: {
        nospawn: true
      }
    }
  },
  jshint: {
    all: ['Gruntfile.js', 'src/*.js', 'src/**/*.js'],
    force: {
      options: { force: true },
      files: { src: ['Gruntfile.js', 'src/*.js', 'src/**/*.js'] }
    }
  },
```

In 0.3 there would be an alert noise and the terminal icon would bounce once. It seems like in 0.4 `force` is making it fail quietly. Can I get the noise back without stopping the server?

**Comment by StephaniesHusband** [comment]
I'm still getting the beep even though jshint says there are "No problems". I thought it was the use of the "newer" plugin on jshint so I removed it but still getting beep when there are no errors. :(
