### ISSUE TITLE
ignore_warning doesn't work

### ISSUE THREAD

**Issue by sekistner** [gruntjs/grunt-contrib-jshint#89]
I can't get this to work, are you sure that's implemented?

``` javascript
grunt.initConfig({
  jshint: {
    all: ['app/**/*.js'],
    ignore_warning: {
      options: {
        '-W069': true
      }
    }
  }
});
```

I can't find `ignore_warning` anywhere in the source code.

**Comment by kafeltz** [comment]
Thank you @shama google sent me here and found your solution.
