### ISSUE TITLE
Error: Cannot find module 'jshint/src/cli/cli after latest JSHint release

### ISSUE THREAD

**Issue by wachunga** [gruntjs/grunt-contrib-jshint#92]
The JSHint crew moved cli.js in [2.1.10](http://jshint.com/blog/2013-08-15/release/) so this plugin is broken.

**Comment by boompig** [comment]
Also ran into this issue in building jquery-ui

**Comment by guy-mograbi-at-gigaspaces** [comment]
+1 me too.

**Comment by englishextra** [comment]
I got it to work at v0.6.5
